/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiAiCoachRouteImport } from './routes/api/ai-coach'
import { Route as AuthenticatedAiCoachIndexRouteImport } from './routes/_authenticated/ai-coach.index'
import { Route as AuthenticatedAiCoachThreadIdRouteImport } from './routes/_authenticated/ai-coach.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiCoachRoute = ApiAiCoachRouteImport.update({
  id: '/api/ai-coach',
  path: '/api/ai-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiCoachIndexRoute =
  AuthenticatedAiCoachIndexRouteImport.update({
    id: '/ai-coach/',
    path: '/ai-coach/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiCoachThreadIdRoute =
  AuthenticatedAiCoachThreadIdRouteImport.update({
    id: '/ai-coach/$threadId',
    path: '/ai-coach/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/ai-coach/$threadId': typeof AuthenticatedAiCoachThreadIdRoute
  '/ai-coach/': typeof AuthenticatedAiCoachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/ai-coach/$threadId': typeof AuthenticatedAiCoachThreadIdRoute
  '/ai-coach': typeof AuthenticatedAiCoachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/_authenticated/ai-coach/$threadId': typeof AuthenticatedAiCoachThreadIdRoute
  '/_authenticated/ai-coach/': typeof AuthenticatedAiCoachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/ai-coach'
    | '/ai-coach/$threadId'
    | '/ai-coach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/ai-coach'
    | '/ai-coach/$threadId'
    | '/ai-coach'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/api/ai-coach'
    | '/_authenticated/ai-coach/$threadId'
    | '/_authenticated/ai-coach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiCoachRoute: typeof ApiAiCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai-coach': {
      id: '/api/ai-coach'
      path: '/api/ai-coach'
      fullPath: '/api/ai-coach'
      preLoaderRoute: typeof ApiAiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-coach/': {
      id: '/_authenticated/ai-coach/'
      path: '/ai-coach'
      fullPath: '/ai-coach/'
      preLoaderRoute: typeof AuthenticatedAiCoachIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-coach/$threadId': {
      id: '/_authenticated/ai-coach/$threadId'
      path: '/ai-coach/$threadId'
      fullPath: '/ai-coach/$threadId'
      preLoaderRoute: typeof AuthenticatedAiCoachThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAiCoachThreadIdRoute: typeof AuthenticatedAiCoachThreadIdRoute
  AuthenticatedAiCoachIndexRoute: typeof AuthenticatedAiCoachIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAiCoachThreadIdRoute: AuthenticatedAiCoachThreadIdRoute,
  AuthenticatedAiCoachIndexRoute: AuthenticatedAiCoachIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiCoachRoute: ApiAiCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
